# Generated by Django 4.1.1 on 2022-09-29 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Number of views'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
