# Generated by Django 4.1.1 on 2022-09-29 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productinfo_views_alter_productinfo_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinfo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
