# Generated by Django 4.1.1 on 2022-09-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productinfo_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='product', to='shop.size'),
        ),
    ]
