# Generated by Django 4.1.1 on 2022-10-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_cartitem_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='files',
            field=models.FileField(blank=True, max_length=255, upload_to='files/%Y/%m/%d/', verbose_name='Files'),
        ),
    ]
