# Generated by Django 4.1.1 on 2022-10-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productinfo_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='files',
        ),
    ]
